services:
  # === MAIN SERVICE (монолит) ===
  main-service:
    build:
      context: ./services/main-service
      dockerfile: Dockerfile
    container_name: main-service
    env_file:
      - .env
    ports:
      - "${MAIN_SERVICE_PORT:-8000}:8000"
    volumes:
      - ./services/main-service:/app
#      - ./services/main-service/requirements/requirements.txt:/app/requirements.txt
    depends_on:
      main-db:
        condition: service_healthy
      valkey:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  # === DATABASE FOR MAIN-SERVICE ===
  main-db:
    image: postgres:15-alpine
    container_name: main-db
    env_file:
      - .env
    ports:
      - "${MAIN_DB_PORT:-5432}:5432"
    volumes:
      - main_db_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${MAIN_DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  valkey:
    image: valkey/valkey:7-alpine
    container_name: valkey
    command: valkey-server --requirepass ${CACHE_PASSWORD} --appendonly yes
    ports:
      - "${CACHE_PORT:-6379}:6379"
    volumes:
      - valkey_data:/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "valkey-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "${API_GATEWAY_PORT:-80}:80"
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - main-service
    networks:
      - app-network
    restart: unless-stopped

volumes:
  main_db_data:
  valkey_data:

networks:
  app-network:
    driver: bridge