events {
    worker_connections 1024;
}

http {
    upstream main-service {
        server main-service:8000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://main-service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # API v1
        location /api/ {
            proxy_pass http://main-service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Health
        location /health {
            proxy_pass http://main-service/health;
            proxy_set_header Host $host;
        }
    }
}